### ISSUE TITLE
"disk fill" cannot deatroy

### ISSUE THREAD

**Issue by alisanguo** [chaosblade-io/chaosblade#19] opened 2019-04-02 05:55 UTC
Type: bug report
 
I used './blade create disk fill --mount-on /home --size 1024' to create disk fill experiment, then I found a file named 'chaos_diskfilled.log.data'  in /home,  but the size of it is 2G (I use 'du -sh /home/chaos_diskfilled.log.data'), and this could not be destroyed by using './blade destroy uid'

**Comment by xcaspar** [comment] 2019-04-02 08:00
It's a bug. The reason for this problem is that `--mount-on` value should be `Mounted on` value, but you passed `Filesystem` value. The blade predicates the `--mount-on` value by `df -h %s | grep -v 'Mounted on' | awk '{print $NF}'` command, so even if you pass the Filesystem value, it will be executed successfully. But when invoking destroy command, it cannot find the disk, so cannot delete the temp file and not process the destroy command result, so it returns success.

Thank you for reporting the issue.

**Comment by alisanguo** [comment] 2019-04-02 08:13
ok. well, I have another question: I found command about mysql by using "./blade create -h", has this been implemented now?

**Comment by xcaspar** [comment] 2019-04-02 09:34
> ok. well, I have another question: I found command about mysql by using "./blade create -h", has this been implemented now?

Yes :-), but currently only for mysql driver in java applications.

**Comment by xcaspar** [comment] 2019-04-02 09:49
> Type: bug report
> 
> I used './blade create disk fill --mount-on /home --size 1024' to create disk fill experiment, then I found a file named 'chaos_diskfilled.log.data' in /home, but the size of it is 2G (I use 'du -sh /home/chaos_diskfilled.log.data'), and this could not be destroyed by using './blade destroy uid'

@alisanguo Currently you can solve it in two ways:
1. Delete temp file blade filled under the disk path which is the corresponding mounted.
2. Re-execute the experiment you just did, but change the value of `--mount-on` to the value of `Mounted on` corresponding to the `Filesystem` you passed in.

**Comment by alisanguo** [comment] 2019-04-02 11:19
I tried the way you provided, but it did not work.  My filesystem is `/dev/mapper/rootvg-lv_home`, and mounted on `/home`.  No matter using filesystem or Mounted on value, it cannot be destroyed.

**Comment by xcaspar** [comment] 2019-04-02 15:54
> I tried the way you provided, but it did not work. My filesystem is `/dev/mapper/rootvg-lv_home`, and mounted on `/home`. No matter using filesystem or Mounted on value, it cannot be destroyed.

Can you provide the result of `mount` command and os version?

**Comment by alisanguo** [comment] 2019-04-03 02:21
### Can you provide the result of mount command and os version?
the result of mount is：

![1791444507](https://user-images.githubusercontent.com/17509906/55448354-05436a80-55fa-11e9-98ae-7c249eceaa27.jpg)

The os version is `red hat enterprise linux release 7.2`

**Comment by xcaspar** [comment] 2019-04-03 03:21
> > Can you provide the result of mount command and os version?
> 
> the result of mount is：
> 
> ![1791444507](https://user-images.githubusercontent.com/17509906/55448354-05436a80-55fa-11e9-98ae-7c249eceaa27.jpg)
> 
> The os version is `red hat enterprise linux release 7.2`

The `blade create disk fill --mount-on /home --size 1024` command you executed is right.

The process of filling a disk is as follows:
1. Invoke `df -h /home | grep -v 'Mounted on' | awk '{print $NF}'` to check the `--mount-on` flag value.
2. Invoke `dd if=/dev/zero of=/home/chaos_filldisk.log.dat bs=1b count=1 iflag=fullblock` command to write 1b data to test execution permissions.
3. Invoke `nohup dd if=/dev/zero of=1024 bs=1M count=%s iflag=fullblock > /dev/null 2>&1 &` command to fill disk.

The stop process for the experiment is as follows:
1. Query the `dd` process id by `ps -ef | grep "/home/chaos_filldisk.log.dat" | grep -v grep |  awk '{print $2}' | tr '\n' ' '` command.
2. If the process id exists, the program will invoke `kill -9 <PID>` command.
3. Invoke `rm -rf /home/chaos_filldisk.log.dat` command to delete the temp file.

Can you follow the above steps to manually execute the command? 
First execute the fill disk steps, check the experimental results: the file size is expected or not. 
Then execute the stop steps to check if it is deleted normally or not.

@alisanguo Thank you.

**Comment by alisanguo** [comment] 2019-04-03 06:00
I followed the above steps to manually execute the command like this:
![1394787171](https://user-images.githubusercontent.com/17509906/55455945-3894f200-5618-11e9-83f5-94bd8f867127.jpg)
but found the result is:
![1822240488](https://user-images.githubusercontent.com/17509906/55456016-70039e80-5618-11e9-984a-2bd42431ae1b.jpg)
I seems that the command ` nohup dd if=/dev/zero of=1024 bs=1M count=%s iflag=fullblock > /dev/null 2>&1 &`  is not right.  A error 'Invalid number %s ' happended

**Comment by xcaspar** [comment] 2019-04-03 06:37
> I followed the above steps to manually execute the command like this:
> ![1394787171](https://user-images.githubusercontent.com/17509906/55456804-988c9800-561a-11e9-8869-ace13478456c.jpg)
> 
> but found the result is:
> ![1822240488](https://user-images.githubusercontent.com/17509906/55456016-70039e80-5618-11e9-984a-2bd42431ae1b.jpg)
> 
> It seems that the command ` nohup dd if=/dev/zero of=1024 bs=1M count=%s iflag=fullblock > /dev/null 2>&1 &` is not right. A error 'Invalid number %s ' happended

@alisanguo I'm very sorry for my mistake. The true command is ` nohup dd if=/dev/zero of=/home/chaos_filldisk.log.dat bs=1M count=1024 iflag=fullblock > /dev/null 2>&1 &`, please retry the above steps. Thank you.

**Comment by alisanguo** [comment] 2019-04-03 09:29
I retry it, and the file `/home/chaos_filldisk.log.dat` can be removed correctly, but I found two questions:
   1. When `I use ll /home/chaos_filldisk.log.dat ` , the size of it is 1024M, but when I use `du -sm /home/chaos_filldisk.log.dat`,  the size of it is 2048, and What is even more strange is that the size of it become 1024M by using  `du -sm /home/chaos_filldisk.log.dat`  later on.
  
![257154442](https://user-images.githubusercontent.com/17509906/55468318-b9aeb200-5635-11e9-9b40-8faaf8ed1567.jpg)

   2. the file `/home/chaos_filldisk.log.dat` cannot be removed by using` ./blade destroy uid`.

**Comment by xcaspar** [comment] 2019-04-03 12:08
> I retry it, and the file `/home/chaos_filldisk.log.dat` can be removed correctly, but I found two questions:
> 
> 1. When `I use ll /home/chaos_filldisk.log.dat ` , the size of it is 1024M, but when I use `du -sm /home/chaos_filldisk.log.dat`,  the size of it is 2048, and What is even more strange is that the size of it become 1024M by using  `du -sm /home/chaos_filldisk.log.dat`  later on.
> 
> ![257154442](https://user-images.githubusercontent.com/17509906/55468318-b9aeb200-5635-11e9-9b40-8faaf8ed1567.jpg)
> 
> 1. the file `/home/chaos_filldisk.log.dat` cannot be removed by using` ./blade destroy uid`.

I tested again and didn't reproduce your problem.
The results of `du -sm /xxx/chaos_filldisk.log.dat` command and `ll /xxx/chaos_filldisk.log.dat` are equal. I destroyed the experiment successfully.

<img width="899" alt="Screen Shot 2019-04-03 at 8 05 50 PM" src="https://user-images.githubusercontent.com/3992234/55477576-0604ec80-564c-11e9-98bc-3b77e7086f60.png">


Please check the uid value is right? @alisanguo

**Comment by xcaspar** [comment] 2019-04-11 08:27
@alisanguo  I will close the issue, please reopen it if your problem has not been solved.

**Closed by xcaspar** 2019-04-11 08:27 UTC
Labels: kind/bug

**Comment by boomblog** [comment] 2019-07-03 08:12
我在mac上执行下面命令会报错：
`blade create disk fill -d --mount-point /home --size 1024`
错误为：
`{"code":604,"success":false,"error":"dd: unknown operand iflag\n exit status 1 exit status 1"}`

看了一下上面的讨论，我直接执行下面的命令也会报错
命令为：
`dd if=/dev/zero of=/home/chaos_filldisk.log.dat bs=1b count=1 iflag=fullblock`
错误为：
`dd: unknown operand iflag`

问题是：是不是mac系统不支持iflag属性？

**Comment by xcaspar** [comment] 2019-07-03 08:19
> 我在mac上执行下面命令会报错：
> `blade create disk fill -d --mount-point /home --size 1024`
> 错误为：
> `{"code":604,"success":false,"error":"dd: unknown operand iflag\n exit status 1 exit status 1"}`
> 
> 看了一下上面的讨论，我直接执行下面的命令也会报错
> 命令为：
> `dd if=/dev/zero of=/home/chaos_filldisk.log.dat bs=1b count=1 iflag=fullblock`
> 错误为：
> `dd: unknown operand iflag`
> 
> 问题是：是不是mac系统不支持iflag属性？

是的，mac 不支持磁盘演练，因为 dd 参数不一样。
