### ISSUE TITLE
connection refused when I prepare jvm

### ISSUE THREAD

**Issue by ueddieu** [chaosblade-io/chaosblade#43] opened 2019-04-18 07:37 UTC
## Issue Description
Type: *bug report* 

### Describe what happened (or what feature you want)
sudo blade prepare jvm -p 23306
{"code":802,"success":false,"error":"Get http://127.0.0.1:38895/sandbox/default/module/http/sandbox-module-mgr/reset?1=1: dial tcp 127.0.0.1:38895: connect: connection refused"}

### Describe what you expected to happen
succeed.

### How to reproduce it (as minimally and precisely as possible)
cannot. 

### Tell us your environment
Linux 3.12.74-60.64.96-default

**Comment by ueddieu** [comment] 2019-04-18 07:39
actually it works if I use standard empty tomcat. but it failed with our application, which runs on Tomcat.
please help to figure out the root cause, or at least explain code 802 means.  thanks.

**Comment by xcaspar** [comment] 2019-04-18 08:46
> actually it works if I use standard empty tomcat. but it failed with our application, which runs on Tomcat.
> please help to figure out the root cause, or at least explain code 802 means. thanks.

@ueddieu The meaning of the 802 error code is that the call to the embedded sandbox service failed.

The root cause of this problem is that the sandbox has been attached, but the blade is using a new port to attach. The reason the blade uses the new port might be:
1. The sandbox is not attached by blade.
2. The chaosblade.dat file has been deleted.

There are two solutions:
a. Restart the application and re-execute the prepare command
b. Execute `sh lib/sandbox/bin/sandbox.sh -S -p PID` command in the chaosblade directory to close sandbox and re-execute the prepare command.

**Comment by xcaspar** [comment] 2019-05-05 01:36
@ueddieu I will close the issue, if you still have problems you can reopen it.

**Closed by xcaspar** 2019-05-05 01:36 UTC
